### ISSUE TITLE
await shouldn’t block

### ISSUE THREAD

**Issue by al45tair** [jyopp/Swift-Async#1]
The await operation in async/await is not supposed to block. Yes, blocking is the simplest implementation thereof (and was [what I originally proposed as a stop-gap on my blog](https://alastairs-place.net/blog/2014/06/09/c-number-like-async-in-swift/) until I’d had chance to write something better).

There are a couple of downsides to blocking on await. The first is that GCD will create lots of threads if you use async/await within an async closure. The second is that you can't safely await from the main thread in a GUI app (or, for that matter, one that uses `dispatch_main`) because it will block the run loop.

The reason C# enthusiasts like async/await so much is that it _is_ safe for them to await on things from the main thread — at least with an async function/method.

Anyway, you don’t really need to solve this issue yourself; just use [my async/await implementation instead](https://bitbucket.org/al45tair/async).

**Comment by jyopp** [comment]
Thanks for the feedback, Alastair! Async.await() is asynchronous. It can induce GCD to use many threads right now, but intentionally not managing threads or thunking into POSIX APIs are design goals for this project. GCD also does a pretty decent job of managing threads itself in a hardware-appropriate way, so the assumption is that if the work is fully expressed to the runtime, GCD will do something appropriate to the hardware configuration.

Handling hundreds or thousands of tasks without excessive thread creation will be a future optimization for this library, most likely handled by having a dedicated concurrent GCD queue monitoring a global dispatch source for scheduling asynchronous await calls.

**Comment by al45tair** [comment]
Yours is certainly an interesting implementation, but your `await<RetT>(workClosure: (T)->RetT) -> Async<RetT>` method is certainly going to cause GCD to create more worker threads, because fundamentally your underlying `await` method blocks.

The alternative is, as you say, to use asynchronous methods like dispatch sources, which would improve your chained `await` call’s behaviour, though the semantics of your implementation are still somewhat different from that in C# — for example, if you want to nest use of `await` with your method, your closures will end up returning `Async<Async<Async<T>>>` and so on, correct?

**Comment by jyopp** [comment]
The return type of any asynchronous await is `Async<RetT>`, where `RetT` is the return type of the provided closure, so there isn't any recursive object wrapping, just execution dependencies. The dependent task takes the precedent task's return value as input, and returns its own value type.

I peppered the readme with as diverse an array of syntax as seemed practical, but this task is one of the most terse; it returns an `Async<UIImage>` for decoding the `NSData` output from the `fetchData` task:

```
// Create a UIImage resource from the data on the default queue
let decodeImage = fetchData.await() {
    UIImage(data: $0.data)
}
```

Here, `decodeImage.await()` returns a UIImage. Calling `decodeImage.await(dispatch_get_main_queue()) {…}` will run the awaiting code on the main queue in the end (such as assigning the image to a UI element).

This is great feedback, it's got me inspired to do some more profiling and maybe implement the dispatch source.

**Comment by al45tair** [comment]
Perhaps an example is in order (albeit a contrived one):

```
let foo = Async<UIImage> {
    let url = NSURL(string:"https://www.google.com/images/srpr/logo11w.png")
    let fetchTask = Async<NSData> {
        NSData(contentsOfURL:url)
    }
    let result = fetchTask.await() {
        UIImage($0)
    }
    return result.await()
}
```

The `return` has to use a blocking await, otherwise the type will be `Async<Async<UIImage>>`, correct?

Using a dispatch source can't fix that as far as I can see. You might be able to improve matters by making it so that closures that return `Async<T>` result in an `Async` whose `await` returns `Async<T>`, which would get rid of the final `await` in the above.

I don't think you can easily get rid of the extra braces that your method requires, though; my version of the above would look like this:

```
let foo = async { () -> UIImage in
    let url = NSURL(string:"https://www.google.com/images/srpr/logo11w.png")
    let fetchTask = async { () -> NSData in
        NSData(contentsOfURL:url)
    }
    let result = await(fetchTask)
    return UIImage(result)
}
```

I don't need to make the `UIImage` in a separate closure because my `await()` is non-blocking.

**Comment by jyopp** [comment]
The examples are not quite the same... `fetchTask.await(){}` returns `Async<UIImage>`, not ~~`Async<Async<UIImage>>`~~.  Modified to be equivalent to the second example, it would be written as follows:

```
let foo = Async<UIImage> {
    let url = NSURL(string:"https://www.google.com/images/srpr/logo11w.png")
    let fetchTask = Async<NSData> {
        NSData(contentsOfURL:url)
    }
    return fetchTask.await() {
        UIImage($0)
    }
}
```

Your library's use of continuations is very cool; I'm just dedicated to using GCD and Swift exclusively, and doing so without Objective-C or any other environment or runtime dependencies. Excessive thread creation could be a problem, but I'm only seeing 50 threads at 2k concurrent tasks in my (admittedly trivial) testing. In any case, I'll update soon to be a little kinder to GCD's scheduler.

**Comment by al45tair** [comment]
Surely that latter version is of type `Async<Async<UIImage>>`? The closure is of type `() -> Async<UIimage>`, so in your generics, `RetT` is `Async<UIImage>`, which makes `Async<RetT>` equal to `Async<Async<UIImage>>`, correct?

:-) It’s a very interesting discussion we’re having here, and I _do_ like your observation that you could make `await()` take a closure to avoid having to use coroutines.

For my part, I need to do some optimisations on my code to reduce the (stack related) overhead.

**Comment by jyopp** [comment]
(Re: above) `RetT` is `UIImage`, since it is inferred by the compiler from the return type of the block being passed.

After several hours of testing and experiments, the current implementation of `await()` has not yielded any further optimizations. Blocking on a dispatch semaphore appears to be very cheap and does not result in large numbers of threads being created. I'm closing this issue since the feature exists and there is no work to be done.

**Comment by jyopp** [comment]
Looking at the example again (which I apparently misread), you're correct about the return type. If one wanted an `Async<Async<UIImage>>` object, it is possible to do that. However, given how `await()` actually interacts with GCD, it would be fair to call the following exactly equivalent to your example:

```
let foo = Async<UIImage> {
    let url = NSURL(string:"https://www.google.com/images/srpr/logo11w.png")
    let fetchTask = Async<NSData> {
        NSData(contentsOfURL:url)
    }
    let result = fetchTask.await(); // dispatch_semaphore yields to other blocks
    return UIImage(result)
}
```
